- hosts: "{{ hostname }}"
  vars:
          - webport: "{{ backport }}"
          - lbport: "{{ frontport }}"
  tasks:
          - name: install haproxy
            package:
                    name: haproxy
                    state: present
          - name: configure haproxy file
            template:
                    src: haproxy.cfg
                    dest: /etc/haproxy/haproxy.cfg
          - name: disable selinux
            selinux:
                    state: disabled
          - name: restart haproxy
            service:
                    name: haproxy
                    state: restarted
          - name: stopping firewall
            command: systemctl stop firewalld
~                                                                                                                                                           